// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeopleSearch.Models;

namespace PeopleSearch.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200522180426_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PeopleSearch.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1963, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Los Angeles",
                            FirstName = "Quentin",
                            LastName = "Tarantino",
                            PhotoFile = "assets/images/photos/Quentin.png",
                            State = "CA",
                            StreetAddress = "234 Main Steet",
                            ZipCode = "90005"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1974, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Beverly Hills",
                            FirstName = "Leonardo",
                            LastName = "DiCaprio",
                            PhotoFile = "assets/images/photos/Leonardo.png",
                            State = "CA",
                            StreetAddress = "24 Church Steet",
                            ZipCode = "90012"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1990, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "New York",
                            FirstName = "Margot",
                            LastName = "Robbie",
                            PhotoFile = "assets/images/photos/Margot.png",
                            State = "NY",
                            StreetAddress = "2346 3rd Ave, Apt. 78A",
                            ZipCode = "10025"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1964, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Long Beach",
                            FirstName = "Brad",
                            LastName = "Pitt",
                            PhotoFile = "assets/images/photos/Brad.png",
                            State = "CA",
                            StreetAddress = "11 S. Sunny Rd.",
                            ZipCode = "90032"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1940, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "New York",
                            FirstName = "Al",
                            LastName = "Pachino",
                            PhotoFile = "assets/images/photos/Al.png",
                            State = "NY",
                            StreetAddress = "45 Broadway St, Ste 300",
                            ZipCode = "10046"
                        });
                });

            modelBuilder.Entity("PeopleSearch.Models.Person", b =>
                {
                    b.OwnsMany("PeopleSearch.Models.Interest", "Interests", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("PersonID")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("PersonID");

                            b1.ToTable("Interest");

                            b1.WithOwner()
                                .HasForeignKey("PersonID");

                            b1.HasData(
                                new
                                {
                                    Id = 1,
                                    Name = "Directing",
                                    PersonID = 1
                                },
                                new
                                {
                                    Id = 2,
                                    Name = "Writing",
                                    PersonID = 1
                                },
                                new
                                {
                                    Id = 3,
                                    Name = "Sailing",
                                    PersonID = 2
                                },
                                new
                                {
                                    Id = 4,
                                    Name = "Playing",
                                    PersonID = 2
                                },
                                new
                                {
                                    Id = 5,
                                    Name = "Hunting",
                                    PersonID = 2
                                },
                                new
                                {
                                    Id = 6,
                                    Name = "Fashion",
                                    PersonID = 3
                                },
                                new
                                {
                                    Id = 7,
                                    Name = "Biking",
                                    PersonID = 4
                                },
                                new
                                {
                                    Id = 8,
                                    Name = "Martial Arts",
                                    PersonID = 4
                                },
                                new
                                {
                                    Id = 9,
                                    Name = "Gambling",
                                    PersonID = 5
                                });
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
